version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis:6.2
    ports:
        - 6379:6379
    networks:
        - messenger-network
  messenger:
    container_name: messenger
    image: jsharper55/redis-messenger:1.0.1
    ports:
        - 8080:8080
    networks:
        - messenger-network
    environment:
        REDIS.ADDRESS: 'redis://redis:6379'
        
networks:
    messenger-network: